In [1]:
import pandas as pd

In [4]:
import os

os.getcwd()

'C:\\Users\\Nagaraju'

In [6]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv")

In [ ]:
# Superstore Sales Analysis and Forecasting

## Project Overview
This project analyzes the Sample Superstore dataset using Python and Pandas to identify business trends, profitability issues, customer performance, shipping efficiency, and forecast future sales.

## Business Questions
1. What are the overall business performance metrics?
2. Which regions and cities generate the highest sales?
3. Which categories and sub-categories are most profitable?
4. Which products and customers generate the highest sales?
5. How do sales and profit change over time?
6. Which products are loss-making?
7. How do discounts affect profitability?
8. Which Region and Ship Mode combinations have the longest delivery times?
9. What are the estimated sales for the next three months?

In [44]:
df.head()

,c,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Delivery Days
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2020,11,3
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2020,11,3
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2020,6,4
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2019,10,7
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2019,10,7

In [45]:
df.shape

(9994, 24)

In [46]:
df.columns

Index(['c', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country/Region', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Year',
       'Month', 'Delivery Days'],
      dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   c               9994 non-null   int64
 1   Order ID        9994 non-null   object
 2   Order Date      9994 non-null   datetime64[ns]
 3   Ship Date       9994 non-null   datetime64[ns]
 4   Ship Mode       9994 non-null   object
 5   Customer ID     9994 non-null   object
 6   Customer Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country/Region  9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal Code     9983 non-null   float64
 12  Region          9994 non-null   object
 13  Product ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub-Category    9994 non-null   object
 16  Product Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
 21  Year            9994 non-null   int32
 22  Month           9994 non-null   int32
 23  Delivery Days   9994 non-null   int64
dtypes: datetime64[ns](2), float64(4), int32(2), int64(3), object(13)
memory usage: 1.8+ MB

In [7]:
#Show only Customer Name and Profit where Profit < 0.
df[df["Profit"] < 0][["Customer Name","Profit"]]

         Customer Name     Profit
3       Sean O'Donnell  -383.0310
14       Harold Pawlan  -123.8580
15       Harold Pawlan    -3.8160
23     Sandra Flanagan    -1.0196
27     Tracy Blumstein -1665.0522
...                ...        ...
9920   Muhammed Yedwab   -35.8176
9921       Alyssa Tate    -4.5936
9931     Keith Herrera   -40.1960
9937    Christine Phan    -1.7772
9962  Corinna Mitchell   -67.6704

[1871 rows x 2 columns]

In [8]:
#Show all Furniture orders.
df[df["Category"] == "Furniture"]

,c,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
5,6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
10,11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9962,9963,CA-2019-168088,19-03-2019,22-03-2019,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041.0,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
9964,9965,CA-2020-146374,05-12-2020,10-12-2020,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711.0,East,FUR-FU-10002671,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320
9980,9981,US-2019-151435,06-09-2019,09-09-2019,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506.0,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
9989,9990,CA-2018-110422,21-01-2018,23-01-2018,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2021-121258,26-02-2021,03-03-2021,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332

In [9]:
#Show the top 5 most profitable orders.
df.sort_values(by="Profit",ascending = False).head(5)

,c,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
6826,6827,CA-2020-118689,02-10-2020,09-10-2020,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760
8153,8154,CA-2021-140151,23-03-2021,25-03-2021,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808
4190,4191,CA-2021-166709,17-11-2021,22-11-2021,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.97,3,0.0,5039.9856
9039,9040,CA-2020-117121,17-12-2020,21-12-2020,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205.0,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.74,13,0.0,4946.3700
4098,4099,CA-2018-116904,23-09-2018,28-09-2018,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407.0,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.95,5,0.0,4630.4755

In [10]:
#Show all rows where Region = "West" and Discount = 0.
df[(df["Region"]=="West") & (df["Discount"]== 0)]

,c,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
5,6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.0,14.1694
6,7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.28,4,0.0,1.9656
9,10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.90,5,0.0,34.4700
17,18,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.50,2,0.0,9.9900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,9978,US-2020-103674,06-12-2020,10-12-2020,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032.0,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.86,7,0.0,0.0000
9986,9987,CA-2020-125794,29-09-2020,03-10-2020,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008.0,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.24,1,0.0,15.2208
9990,9991,CA-2021-121258,26-02-2021,03-03-2021,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.0,15.6332
9992,9993,CA-2021-121258,26-02-2021,03-03-2021,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.3200
9993,9994,CA-2021-119914,04-05-2021,09-05-2021,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.9480

In [11]:
df.groupby("Category")

In [12]:
df.groupby("Category")["Profit"].sum()

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

In [13]:
df.groupby("Category")["Profit"].mean()

Category
Furniture           8.699327
Office Supplies    20.327050
Technology         78.752002
Name: Profit, dtype: float64

In [14]:
df.groupby("Category")["Order ID"].count()

Category
Furniture          2121
Office Supplies    6026
Technology         1847
Name: Order ID, dtype: int64

In [15]:
df.groupby("Category").agg({"Profit":"sum",
"Sales":"sum"})

                      Profit        Sales
Category
Furniture         18451.2728  741999.7953
Office Supplies  122490.8008  719047.0320
Technology       145454.9481  836154.0330

In [16]:
df.groupby("Category").agg({
    "Profit":["sum","mean"],
    "Sales" :["sum","mean"]

})

                      Profit                   Sales
                         sum       mean          sum        mean
Category
Furniture         18451.2728   8.699327  741999.7953  349.834887
Office Supplies  122490.8008  20.327050  719047.0320  119.324101
Technology       145454.9481  78.752002  836154.0330  452.709276

In [17]:
result = df.groupby("Category")["Sales"].sum()
result.reset_index()

          Category        Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [19]:
#What are the overall Sales, Profit, Quantity sold, and number of unique Orders in the dataset?
Total_Sales = df["Sales"].sum()
Total_Profit = df["Profit"].sum()
Total_Quantity = df["Quantity"].sum()
Total_Orders = df["Order ID"].nunique()

print("Total_Sales",Total_Sales)
print("Total_Profit",Total_Profit)
print("Total_Quantity",Total_Quantity)
print("Total_Orders",Total_Orders)

Total_Sales 2297200.8603
Total_Profit 286397.0217
Total_Quantity 37873
Total_Orders 5009

In [20]:
#Which regions generate the highest total sales?
df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

In [21]:
#Which 10 cities generate the highest total sales?
df.groupby("City")["Sales"].sum().sort_values(ascending=False).head(10)

City
New York City    256368.1610
Los Angeles      175851.3410
Seattle          119540.7420
San Francisco    112669.0920
Philadelphia     109077.0130
Houston           64504.7604
Chicago           48539.5410
San Diego         47521.0290
Jacksonville      44713.1830
Springfield       43054.3420
Name: Sales, dtype: float64

In [22]:
#Which product categories generate the highest total profit?
df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

In [23]:
#Within each category, which sub-categories generate the highest total profit?
df.groupby(["Category","Sub-Category"])["Profit"].sum().sort_values(ascending=False)

Category         Sub-Category
Technology       Copiers         55617.8249
                 Phones          44515.7306
                 Accessories     41936.6357
Office Supplies  Paper           34053.5693
                 Binders         30221.7633
Furniture        Chairs          26590.1663
Office Supplies  Storage         21278.8264
                 Appliances      18138.0054
Furniture        Furnishings     13059.1436
Office Supplies  Envelopes        6964.1767
                 Art              6527.7870
                 Labels           5546.2540
Technology       Machines         3384.7569
Office Supplies  Fasteners         949.5182
                 Supplies        -1189.0995
Furniture        Bookcases       -3472.5560
                 Tables         -17725.4811
Name: Profit, dtype: float64

In [24]:
#What are the top 10 products by total sales?
top_products = (
    df.groupby("Product Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)
print (top_products)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [25]:
#Who are the top 10 customers by total sales?
top_customers = (
    df.groupby(["Customer ID", "Customer Name"])["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(top_customers)

Customer ID  Customer Name
SM-20320     Sean Miller           25043.050
TC-20980     Tamara Chand          19052.218
RB-19360     Raymond Buch          15117.339
TA-21385     Tom Ashbrook          14595.620
AB-10105     Adrian Barton         14473.571
KL-16645     Ken Lonsdale          14175.229
SC-20095     Sanjit Chand          14142.334
HL-15040     Hunter Lopez          12873.298
SE-20110     Sanjit Engle          12209.438
CC-12370     Christopher Conant    12129.072
Name: Sales, dtype: float64

In [26]:
# How do total sales change month by month?
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)
df["year"] = df["Order Date"].dt.year
df["month"] = df["Order Date"].dt.month

monthly_sales = (
    df.groupby(["year", "month"])["Sales"]
      .sum()
      .sort_index()
)

print(monthly_sales)

year  month
2018  1         14236.8950
      2          4519.8920
      3         55691.0090
      4         28295.3450
      5         23648.2870
      6         34595.1276
      7         33946.3930
      8         27909.4685
      9         81777.3508
      10        31453.3930
      11        78628.7167
      12        69545.6205
2019  1         18174.0756
      2         11951.4110
      3         38726.2520
      4         34195.2085
      5         30131.6865
      6         24797.2920
      7         28765.3250
      8         36898.3322
      9         64595.9180
      10        31404.9235
      11        75972.5635
      12        74919.5212
2020  1         18542.4910
      2         22978.8150
      3         51715.8750
      4         38750.0390
      5         56987.7280
      6         40344.5340
      7         39261.9630
      8         31115.3743
      9         73410.0249
      10        59687.7450
      11        79411.9658
      12        96999.0430
2021  1         43971.3740
      2         20301.1334
      3         58872.3528
      4         36521.5361
      5         44261.1102
      6         52981.7257
      7         45264.4160
      8         63120.8880
      9         87866.6520
      10        77776.9232
      11       118447.8250
      12        83829.3188
Name: Sales, dtype: float64

In [27]:
#Which 10 products generated the highest total sales but still had an overall negative profit?

product_analysis = df.groupby("Product Name").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum")
)

loss_analysis = (product_analysis[product_analysis["Total_Profit"] < 0].sort_values("Total_Sales", ascending=False).head(10))
print (loss_analysis)

                                                    Total_Sales  Total_Profit
Product Name
Cisco TelePresence System EX90 Videoconferencin...   22638.4800    -1811.0784
GBC DocuBind P400 Electric Binding System            17965.0680    -1878.1662
High Speed Automatic Electric Letter Opener          17030.3120     -262.0048
Lexmark MX611dhe Monochrome Laser Printer            16829.9010    -4589.9730
Martin Yale Chadless Opener Electric Letter Opener   16656.2000    -1299.1836
Riverside Palais Royal Lawyers Bookcase, Royale...   15610.9656     -669.5448
Bretford Rectangular Conference Table Tops           12995.2915     -327.2331
Cubify CubeX 3D Printer Double Head Print            11099.9630    -8879.9704
Chromcraft Bull-Nose Wood Oval Conference Table...    9917.6400    -2876.1156
Bush Advantage Collection Racetrack Conference ...    9544.7250    -1934.3976

In [28]:
#Which 10 customers have the highest total sales, and how much total profit did each of them generate?
top_customers = (
    df.groupby(["Customer ID", "Customer Name"])
      .agg(
          total_sales=("Sales", "sum"),
          total_profit=("Profit", "sum")
      )
      .sort_values("total_sales", ascending=False)
      .head(10)
)

print(top_customers)

                                total_sales  total_profit
Customer ID Customer Name
SM-20320    Sean Miller           25043.050    -1980.7393
TC-20980    Tamara Chand          19052.218     8981.3239
RB-19360    Raymond Buch          15117.339     6976.0959
TA-21385    Tom Ashbrook          14595.620     4703.7883
AB-10105    Adrian Barton         14473.571     5444.8055
KL-16645    Ken Lonsdale          14175.229      806.8550
SC-20095    Sanjit Chand          14142.334     5757.4119
HL-15040    Hunter Lopez          12873.298     5622.4292
SE-20110    Sanjit Engle          12209.438     2650.6769
CC-12370    Christopher Conant    12129.072     2177.0493

In [29]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv")

In [30]:
#Which region has the highest Average Order Value (AOV)?
region_aov =( df.groupby("Region")
    .agg(
        Total_sales = ("Sales","sum"),
        unique_orders = ("Order ID", "nunique")
    )
)
region_aov["AOV"] = (region_aov["Total_sales"]/region_aov["unique_orders"])
region_aov = region_aov.sort_values("AOV", ascending=False)

print (region_aov)

         Total_sales  unique_orders         AOV
Region
East     678781.2400           1401  484.497673
South    391721.9050            822  476.547330
West     725457.8245           1611  450.315223
Central  501239.8908           1175  426.587141

In [31]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month

In [32]:
#Which months had the highest and lowest total Sales and Profit?
monthly_performance = (
    df.groupby(["Year", "Month"])
      .agg(
          total_sales=("Sales", "sum"),
          total_profit=("Profit", "sum")
      )
)

monthly_performance = monthly_performance.sort_index()

print(monthly_performance)

            total_sales  total_profit
Year Month
2018 1       14236.8950     2450.1907
     2        4519.8920      862.3084
     3       55691.0090      498.7299
     4       28295.3450     3488.8352
     5       23648.2870     2738.7096
     6       34595.1276     4976.5244
     7       33946.3930     -841.4826
     8       27909.4685     5318.1050
     9       81777.3508     8328.0994
     10      31453.3930     3448.2573
     11      78628.7167     9292.1269
     12      69545.6205     8983.5699
2019 1       18174.0756    -3281.0070
     2       11951.4110     2813.8508
     3       38726.2520     9732.0978
     4       34195.2085     4187.4962
     5       30131.6865     4667.8690
     6       24797.2920     3335.5572
     7       28765.3250     3288.6483
     8       36898.3322     5355.8084
     9       64595.9180     8209.1627
     10      31404.9235     2817.3660
     11      75972.5635    12474.7884
     12      74919.5212     8016.9659
2020 1       18542.4910     2824.8233
     2       22978.8150     5004.5795
     3       51715.8750     3611.9680
     4       38750.0390     2977.8149
     5       56987.7280     8662.1464
     6       40344.5340     4750.3781
     7       39261.9630     4432.8779
     8       31115.3743     2062.0693
     9       73410.0249     9328.6576
     10      59687.7450    16243.1425
     11      79411.9658     4011.4075
     12      96999.0430    17885.3093
2021 1       43971.3740     7140.4391
     2       20301.1334     1613.8720
     3       58872.3528    14751.8915
     4       36521.5361      933.2900
     5       44261.1102     6342.5828
     6       52981.7257     8223.3357
     7       45264.4160     6952.6212
     8       63120.8880     9040.9557
     9       87866.6520    10991.5556
     10      77776.9232     9275.2755
     11     118447.8250     9690.1037
     12      83829.3188     8483.3468

In [33]:
#At what discount level does profit turn negative for each category?
discount_analysis = (
    df.groupby(["Category", "Discount"])
      .agg(
          total_profit=("Profit", "sum"),
          total_sales=("Sales", "sum"),
          average_profit=("Profit", "mean")
      )
)
discount_analysis[discount_analysis["total_profit"] < 0]

                          total_profit  total_sales  average_profit
Category        Discount
Furniture       0.30       -10695.3169   99470.3500      -48.177103
                0.32        -2391.1377   14493.4588      -88.560656
                0.40       -16187.3968   45614.4060     -215.831957
                0.45        -2493.1111    5484.9740     -226.646464
                0.50       -12871.1990   20983.4700     -238.355537
                0.60        -5944.6552    6644.7000      -43.077212
                0.70        -3894.9394    2459.3820     -259.662627
Office Supplies 0.70       -16601.0984   22559.3910      -43.687101
                0.80       -30539.0392   16963.7560     -101.796797
Technology      0.40        -6869.6536   70803.3780      -52.440104
                0.50        -7635.2291   37935.0700     -636.269092
                0.70       -19579.3191   15601.5090     -851.274743

In [34]:
#Which Region and Ship Mode combinations have the longest average delivery time?

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y")
df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],format="%d-%m-%Y")
df["Delivery Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

shipping_analysis = (
    df.groupby(["Region", "Ship Mode"])
      .agg(
          avg_delivery_days=("Delivery Days", "mean"),
          max_delivery_days=("Delivery Days", "max"),
          total_orders=("Order ID", "nunique")
      )
      .reset_index()
      .sort_values(
          "avg_delivery_days",
          ascending=False
      )
)

print(shipping_analysis)

     Region       Ship Mode  avg_delivery_days  max_delivery_days  \
15     West  Standard Class           5.058980                  7
11    South  Standard Class           4.995893                  7
3   Central  Standard Class           4.990271                  7
7      East  Standard Class           4.968320                  7
2   Central    Second Class           3.331183                  5
6      East    Second Class           3.266038                  5
10    South    Second Class           3.194529                  5
14     West    Second Class           3.167472                  5
0   Central     First Class           2.317726                  3
4      East     First Class           2.224490                  4
8     South     First Class           2.111111                  3
12     West     First Class           2.097087                  3
13     West        Same Day           0.102703                  1
1   Central        Same Day           0.033333                  1
9     South        Same Day           0.012048                  1
5      East        Same Day           0.000000                  0

    total_orders
15           956
11           495
3            715
7            828
2            224
6            266
10           164
14           310
0            174
4            233
8            124
12           256
13            89
1             62
9             39
5             74

In [35]:
#Based on the historical monthly sales trend, what will the estimated total sales be for the next 3 months?

monthly_sales =( 
    df.groupby(["Year","Month"])
    .agg(
        Total_sales = ("Sales","sum")
        )           
.reset_index()
.sort_values(["Year","Month"])
)              
print(monthly_sales)

monthly_sales["Month_num"] = range(len(monthly_sales))

    Year  Month  Total_sales
0   2018      1   14236.8950
1   2018      2    4519.8920
2   2018      3   55691.0090
3   2018      4   28295.3450
4   2018      5   23648.2870
5   2018      6   34595.1276
6   2018      7   33946.3930
7   2018      8   27909.4685
8   2018      9   81777.3508
9   2018     10   31453.3930
10  2018     11   78628.7167
11  2018     12   69545.6205
12  2019      1   18174.0756
13  2019      2   11951.4110
14  2019      3   38726.2520
15  2019      4   34195.2085
16  2019      5   30131.6865
17  2019      6   24797.2920
18  2019      7   28765.3250
19  2019      8   36898.3322
20  2019      9   64595.9180
21  2019     10   31404.9235
22  2019     11   75972.5635
23  2019     12   74919.5212
24  2020      1   18542.4910
25  2020      2   22978.8150
26  2020      3   51715.8750
27  2020      4   38750.0390
28  2020      5   56987.7280
29  2020      6   40344.5340
30  2020      7   39261.9630
31  2020      8   31115.3743
32  2020      9   73410.0249
33  2020     10   59687.7450
34  2020     11   79411.9658
35  2020     12   96999.0430
36  2021      1   43971.3740
37  2021      2   20301.1334
38  2021      3   58872.3528
39  2021      4   36521.5361
40  2021      5   44261.1102
41  2021      6   52981.7257
42  2021      7   45264.4160
43  2021      8   63120.8880
44  2021      9   87866.6520
45  2021     10   77776.9232
46  2021     11  118447.8250
47  2021     12   83829.3188

In [37]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\nagaraju\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\nagaraju\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\nagaraju\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\nagaraju\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\nagaraju\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\nagaraju\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\Nagaraju\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [38]:
from sklearn.linear_model import LinearRegression

In [40]:
monthly_sales["Month_Number"] = range(len(monthly_sales))

In [41]:
X = monthly_sales[["Month_Number"]]
y = monthly_sales["Total_sales"]

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [49]:
future_months = pd.DataFrame({
    "Month_Number": [
        len(monthly_sales),
        len(monthly_sales) + 1,
        len(monthly_sales) + 2
    ]
})

forecast = model.predict(future_months)

print(forecast)

[69957.53579787 70859.54333018 71761.55086249]

In [ ]:
#### Key Insight

A baseline Linear Regression model was used to estimate sales for the next three months based on historical monthly sales trends.

The forecast predicts a gradual increase in sales. However, this model should be considered a baseline because it does not account for seasonality, promotions, or other external business factors.